<template>
  <!-- Grid宫格 -->
  <van-grid :column-num="2" :gutter="10" square>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-1.jpg" />
      <p>文字</p>
    </van-grid-item>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-2.jpg" />
      <p>文字</p>
    </van-grid-item>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-2.jpg" />
      <p>文字</p>
    </van-grid-item>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-1.jpg" />
      <p>文字</p>
    </van-grid-item>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-1.jpg" />
      <p>文字</p>
    </van-grid-item>
    <van-grid-item>
      <van-image src="https://img.yzcdn.cn/vant/apple-2.jpg" />
      <p>文字</p>
    </van-grid-item>
  </van-grid>
</template>

<script>
export default {

}
</script>

<style scoped>
  
</style>
